// <auto-generated />
using System;
using GestorStock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorStock.Data.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("GestorStock.Model.Entities.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Familias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "INTERCAMBIADORES"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "MERCADOS"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "SETAS DE SEVILLA"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "EXPLOTACIONES"
                        });
                });

            modelBuilder.Entity("GestorStock.Model.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Proveedor Demo"
                        });
                });

            modelBuilder.Entity("GestorStock.Model.Entities.RepuestoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TipoSoporteId")
                        .HasColumnType("int");

                    b.Property<int?>("UbicacionProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TipoSoporteId");

                    b.HasIndex("UbicacionProductoId");

                    b.ToTable("RepuestoCatalogos");
                });

            modelBuilder.Entity("GestorStock.Model.Entities.TipoSoporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TipoSoportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pantalla LED"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mupis Digital"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Monoposte"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Skyled"
                        });
                });

            modelBuilder.Entity("GestorStock.Model.Entities.UbicacionProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("UbicacionProductos");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            FamiliaId = 1,
                            Nombre = "Skyled moncloa"
                        },
                        new
                        {
                            Id = 6,
                            FamiliaId = 1,
                            Nombre = "Skyled plaza elíptica fachada"
                        },
                        new
                        {
                            Id = 7,
                            FamiliaId = 1,
                            Nombre = "Skyled plaza elíptica lateral a-42"
                        },
                        new
                        {
                            Id = 15,
                            FamiliaId = 1,
                            Nombre = "Skyled estación autobuses donostia pantalla 4x1 entrada"
                        },
                        new
                        {
                            Id = 16,
                            FamiliaId = 1,
                            Nombre = "Skyled estación autobuses donostia cortina digital 2x2 lateral"
                        },
                        new
                        {
                            Id = 17,
                            FamiliaId = 1,
                            Nombre = "Pantalla led exterior pasaje acceso estación autobuses donostia"
                        },
                        new
                        {
                            Id = 18,
                            FamiliaId = 1,
                            Nombre = "Pantalla led pasillo acceso estación autobuses donostia"
                        },
                        new
                        {
                            Id = 19,
                            FamiliaId = 1,
                            Nombre = "Pantalla led 2x1.50 friso escalera acceso estación autobuses donostia"
                        },
                        new
                        {
                            Id = 20,
                            FamiliaId = 1,
                            Nombre = "Pantalla lcd 55\" hall estación autobuses donostia junto restaurante"
                        },
                        new
                        {
                            Id = 21,
                            FamiliaId = 1,
                            Nombre = "Pantalla led gran formato (bilbao)"
                        },
                        new
                        {
                            Id = 22,
                            FamiliaId = 1,
                            Nombre = "Circuito handia bilbao (bilbao)"
                        },
                        new
                        {
                            Id = 23,
                            FamiliaId = 1,
                            Nombre = "Circuito kaixo bilbao (bilbao)"
                        },
                        new
                        {
                            Id = 24,
                            FamiliaId = 1,
                            Nombre = "Columna digital conexión metro a islas 2-3 planta 3 (moncloa)"
                        },
                        new
                        {
                            Id = 25,
                            FamiliaId = 1,
                            Nombre = "Pantalla digital acceso metro isla 2 (moncloa)"
                        },
                        new
                        {
                            Id = 26,
                            FamiliaId = 1,
                            Nombre = "Pantalla digital acceso metro isla 3 (moncloa)"
                        },
                        new
                        {
                            Id = 27,
                            FamiliaId = 1,
                            Nombre = "Pantalla digital acceso p° moret (moncloa)"
                        },
                        new
                        {
                            Id = 28,
                            FamiliaId = 1,
                            Nombre = "40 mupis digitales (moncloa)"
                        },
                        new
                        {
                            Id = 29,
                            FamiliaId = 1,
                            Nombre = "20 mupis digitales (plaza elíptica)"
                        },
                        new
                        {
                            Id = 30,
                            FamiliaId = 1,
                            Nombre = "Pantalla digital nivel -1 (plaza elíptica)"
                        },
                        new
                        {
                            Id = 31,
                            FamiliaId = 2,
                            Nombre = "Mercado plaza de abastos"
                        },
                        new
                        {
                            Id = 32,
                            FamiliaId = 2,
                            Nombre = "Mercado de chamartín"
                        },
                        new
                        {
                            Id = 33,
                            FamiliaId = 2,
                            Nombre = "Mercado de correos"
                        },
                        new
                        {
                            Id = 34,
                            FamiliaId = 2,
                            Nombre = "Mercado central zaragoza"
                        },
                        new
                        {
                            Id = 35,
                            FamiliaId = 2,
                            Nombre = "Mercado de el este"
                        },
                        new
                        {
                            Id = 36,
                            FamiliaId = 2,
                            Nombre = "Mercado de la imprenta valencia"
                        },
                        new
                        {
                            Id = 37,
                            FamiliaId = 2,
                            Nombre = "Mercado de la carne"
                        },
                        new
                        {
                            Id = 38,
                            FamiliaId = 2,
                            Nombre = "Mercado los mostenses"
                        },
                        new
                        {
                            Id = 39,
                            FamiliaId = 2,
                            Nombre = "Mercado vell"
                        },
                        new
                        {
                            Id = 40,
                            FamiliaId = 2,
                            Nombre = "Mercado de la ribera"
                        },
                        new
                        {
                            Id = 41,
                            FamiliaId = 2,
                            Nombre = "Mercado de san antón"
                        },
                        new
                        {
                            Id = 42,
                            FamiliaId = 2,
                            Nombre = "Mercado de san antón parking"
                        },
                        new
                        {
                            Id = 43,
                            FamiliaId = 2,
                            Nombre = "Mercado san fernando"
                        },
                        new
                        {
                            Id = 44,
                            FamiliaId = 2,
                            Nombre = "Mercado de san ildefonso"
                        },
                        new
                        {
                            Id = 45,
                            FamiliaId = 2,
                            Nombre = "Mercado de san miguel"
                        },
                        new
                        {
                            Id = 46,
                            FamiliaId = 2,
                            Nombre = "Mercado de triana"
                        },
                        new
                        {
                            Id = 47,
                            FamiliaId = 2,
                            Nombre = "Mercado del val"
                        },
                        new
                        {
                            Id = 48,
                            FamiliaId = 2,
                            Nombre = "Cúpula del milenio (valladolid)"
                        },
                        new
                        {
                            Id = 10,
                            FamiliaId = 3,
                            Nombre = "Skyled las setas de sevilla columna"
                        },
                        new
                        {
                            Id = 11,
                            FamiliaId = 3,
                            Nombre = "Skyled las setas de sevilla mupi"
                        },
                        new
                        {
                            Id = 12,
                            FamiliaId = 3,
                            Nombre = "Skyled las setas de sevilla rampa"
                        },
                        new
                        {
                            Id = 13,
                            FamiliaId = 3,
                            Nombre = "Skyled las setas de sevilla mercado"
                        },
                        new
                        {
                            Id = 14,
                            FamiliaId = 3,
                            Nombre = "Skyled las setas de sevilla parasol"
                        },
                        new
                        {
                            Id = 1,
                            FamiliaId = 4,
                            Nombre = "Skyled basauri (cc bilbondo)"
                        },
                        new
                        {
                            Id = 2,
                            FamiliaId = 4,
                            Nombre = "Skyled cc niessen"
                        },
                        new
                        {
                            Id = 3,
                            FamiliaId = 4,
                            Nombre = "Skyled cc zubiarte (cc zubiarte)"
                        },
                        new
                        {
                            Id = 4,
                            FamiliaId = 4,
                            Nombre = "Skyled granada (cc granaita)"
                        },
                        new
                        {
                            Id = 8,
                            FamiliaId = 4,
                            Nombre = "Skyled valencia"
                        },
                        new
                        {
                            Id = 9,
                            FamiliaId = 4,
                            Nombre = "Skyled valladolid (cc vallsur)"
                        });
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionIncidencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Factura")
                        .HasColumnType("longtext");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaIncidencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Incidencia")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pedido demo",
                            DescripcionIncidencia = "",
                            Factura = "",
                            FamiliaId = 1,
                            FechaCreacion = new DateTime(2025, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Incidencia = false
                        });
                });

            modelBuilder.Entity("Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoRepuesto")
                        .HasColumnType("int");

                    b.Property<int>("TipoSoporteId")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoSoporteId");

                    b.HasIndex("UbicacionProductoId");

                    b.ToTable("Repuestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            Descripcion = "",
                            FamiliaId = 1,
                            Nombre = "Repuesto Demo",
                            PedidoId = 1,
                            Precio = 0m,
                            ProveedorId = 1,
                            TipoRepuesto = 0,
                            TipoSoporteId = 1,
                            UbicacionProductoId = 5
                        });
                });

            modelBuilder.Entity("GestorStock.Model.Entities.RepuestoCatalogo", b =>
                {
                    b.HasOne("GestorStock.Model.Entities.Familia", "Familia")
                        .WithMany("Catalogo")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorStock.Model.Entities.TipoSoporte", "TipoSoporte")
                        .WithMany()
                        .HasForeignKey("TipoSoporteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestorStock.Model.Entities.UbicacionProducto", "UbicacionProducto")
                        .WithMany()
                        .HasForeignKey("UbicacionProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Familia");

                    b.Navigation("TipoSoporte");

                    b.Navigation("UbicacionProducto");
                });

            modelBuilder.Entity("GestorStock.Model.Entities.UbicacionProducto", b =>
                {
                    b.HasOne("GestorStock.Model.Entities.Familia", "Familia")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.HasOne("GestorStock.Model.Entities.Familia", "Familia")
                        .WithMany("Pedidos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Repuesto", b =>
                {
                    b.HasOne("GestorStock.Model.Entities.Familia", "Familia")
                        .WithMany("Repuestos")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pedido", "Pedido")
                        .WithMany("Repuestos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorStock.Model.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorStock.Model.Entities.TipoSoporte", "TipoSoporte")
                        .WithMany("Repuestos")
                        .HasForeignKey("TipoSoporteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorStock.Model.Entities.UbicacionProducto", "UbicacionProducto")
                        .WithMany("Repuestos")
                        .HasForeignKey("UbicacionProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Pedido");

                    b.Navigation("Proveedor");

                    b.Navigation("TipoSoporte");

                    b.Navigation("UbicacionProducto");
                });

            modelBuilder.Entity("GestorStock.Model.Entities.Familia", b =>
                {
                    b.Navigation("Catalogo");

                    b.Navigation("Pedidos");

                    b.Navigation("Repuestos");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("GestorStock.Model.Entities.TipoSoporte", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("GestorStock.Model.Entities.UbicacionProducto", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Navigation("Repuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
